export type AssetCategory =
  | 'character'
  | 'enemy'
  | 'portrait'
  | 'tileset'
  | 'map'
  | 'ui'
  | 'icon'
  | 'background'
  | 'audio'
  | 'structure';

export type AssetStatus = 'placeholder' | 'final';

export interface AssetDimensions {
  width: number;
  height: number;
}

export interface AssetDefinition {
  id: string;
  category: AssetCategory;
  intendedUse: string;
  /** Path relative to /assets/ under public/, e.g. "sprites/characters/player.png". */
  filePath: string;
  /** null for asset types dimensions don't apply to (audio, Tiled maps). */
  dimensions: AssetDimensions | null;
  /** One animation frame's size within `dimensions` - present only for sprite sheets. Absent
   *  means the whole image is a single static frame (every asset today except sprite.player).
   *  Columns/rows are derived arithmetically (dimensions ÷ frameSize) rather than stored, since no
   *  consumer needs ragged rows. */
  frameSize?: AssetDimensions;
  status: AssetStatus;
  notes: string;
}

/**
 * Single source of truth for every game asset. Code never imports an image/audio/map
 * file path directly — it looks the asset up here by id via assetManager.getAsset().
 * Swapping a placeholder for final art is a one-line edit to this file.
 */
export const ASSET_REGISTRY: AssetDefinition[] = [
  {
    id: 'tileset.tiny-dungeon',
    category: 'tileset',
    intendedUse: 'Shared 16x16 tileset for Ash Hallow, Ironwood Trail, and Hollow Rail Mine maps (walls, floors, dungeon/town dressing)',
    filePath: 'tilesets/tiny-dungeon.png',
    dimensions: { width: 192, height: 176 },
    status: 'placeholder',
    notes: 'Kenney "Tiny Dungeon" pack, CC0 1.0, kenney.nl/assets/tiny-dungeon. 12x11 grid of 16x16 tiles.',
  },
  {
    id: 'ui.panel-border-default',
    category: 'ui',
    intendedUse: 'Default 9-slice panel background for dialogue box, menus, and other JRPG UI panels',
    filePath: 'ui/panel-border-000.png',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Kenney "Fantasy UI Borders" pack, CC0 1.0, kenney.nl/assets/fantasy-ui-borders. Use as CSS border-image with ~16px slice insets.',
  },
  {
    id: 'ui.panel-border-accent',
    category: 'ui',
    intendedUse: 'Accent 9-slice panel background for emphasized UI (e.g. victory/level-up panels)',
    filePath: 'ui/panel-border-004.png',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Kenney "Fantasy UI Borders" pack, CC0 1.0, kenney.nl/assets/fantasy-ui-borders. Use as CSS border-image with ~16px slice insets.',
  },
  {
    id: 'portrait.elias-rowan',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for elias-rowan',
    filePath: 'portraits/elias-rowan.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.elias-rowan',
    category: 'character',
    intendedUse: 'Overworld sprite for elias-rowan (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/elias-rowan.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.mara-ash',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for mara-ash',
    filePath: 'portraits/mara-ash.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.mara-ash',
    category: 'character',
    intendedUse: 'Overworld sprite for mara-ash (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/mara-ash.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.finn-rowan',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for finn-rowan',
    filePath: 'portraits/finn-rowan.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.finn-rowan',
    category: 'character',
    intendedUse: 'Overworld sprite for finn-rowan (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/finn-rowan.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.silas-flint',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for silas-flint',
    filePath: 'portraits/silas-flint.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.silas-flint',
    category: 'character',
    intendedUse: 'Overworld sprite for silas-flint (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/silas-flint.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.juniper-reed',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for juniper-reed',
    filePath: 'portraits/juniper-reed.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.juniper-reed',
    category: 'character',
    intendedUse: 'Overworld sprite for juniper-reed (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/juniper-reed.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.nell-ashby',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for nell-ashby',
    filePath: 'portraits/nell-ashby.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.nell-ashby',
    category: 'character',
    intendedUse: 'Overworld sprite for nell-ashby (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/nell-ashby.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.aldren-stone',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for aldren-stone',
    filePath: 'portraits/aldren-stone.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.aldren-stone',
    category: 'character',
    intendedUse: 'Overworld sprite for aldren-stone (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/aldren-stone.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.tessa-ironhand',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for tessa-ironhand',
    filePath: 'portraits/tessa-ironhand.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.tessa-ironhand',
    category: 'character',
    intendedUse: 'Overworld sprite for tessa-ironhand (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/tessa-ironhand.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.willow-briar',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for willow-briar',
    filePath: 'portraits/willow-briar.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.willow-briar',
    category: 'character',
    intendedUse: 'Overworld sprite for willow-briar (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/willow-briar.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.historian-miriam',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for historian-miriam',
    filePath: 'portraits/historian-miriam.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.historian-miriam',
    category: 'character',
    intendedUse: 'Overworld sprite for historian-miriam (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/historian-miriam.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.mayor-eleanor-ashcroft',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for mayor-eleanor-ashcroft',
    filePath: 'portraits/mayor-eleanor-ashcroft.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.mayor-eleanor-ashcroft',
    category: 'character',
    intendedUse: 'Overworld sprite for mayor-eleanor-ashcroft (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/mayor-eleanor-ashcroft.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.hunter-garrick',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for hunter-garrick',
    filePath: 'portraits/hunter-garrick.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.hunter-garrick',
    category: 'character',
    intendedUse: 'Overworld sprite for hunter-garrick (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/hunter-garrick.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.spirit-child',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for spirit-child',
    filePath: 'portraits/spirit-child.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.spirit-child',
    category: 'character',
    intendedUse: 'Overworld sprite for spirit-child (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/spirit-child.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.ranger-caleb',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for ranger-caleb',
    filePath: 'portraits/ranger-caleb.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.ranger-caleb',
    category: 'character',
    intendedUse: 'Overworld sprite for ranger-caleb (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/ranger-caleb.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.player',
    category: 'character',
    intendedUse: 'Player overworld sprite - 4-direction walk+run sheet (8 rows x 4 frames of 32x32)',
    filePath: 'sprites/characters/player-sprite.png',
    dimensions: { width: 128, height: 256 },
    frameSize: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'User-provided sprite sheet. Row order: walk-down, walk-left, walk-up, walk-right, run-down, run-left, run-up, run-right. Placeholder - user intends to replace it later.',
  },
  {
    id: 'battle.enemy.mothling',
    category: 'enemy',
    intendedUse: 'Battle sprite for mothling',
    filePath: 'sprites/enemies/mothling.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.greater-mothling',
    category: 'enemy',
    intendedUse: 'Battle sprite for greater-mothling',
    filePath: 'sprites/enemies/greater-mothling.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.restless-miner',
    category: 'enemy',
    intendedUse: 'Battle sprite for restless-miner',
    filePath: 'sprites/enemies/restless-miner.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.foreman-wraith',
    category: 'enemy',
    intendedUse: 'Battle sprite for foreman-wraith',
    filePath: 'sprites/enemies/foreman-wraith.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.coal-spirit',
    category: 'enemy',
    intendedUse: 'Battle sprite for coal-spirit',
    filePath: 'sprites/enemies/coal-spirit.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.coal-wraith',
    category: 'enemy',
    intendedUse: 'Battle sprite for coal-wraith',
    filePath: 'sprites/enemies/coal-wraith.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.cliff-wolf',
    category: 'enemy',
    intendedUse: 'Battle sprite for cliff-wolf',
    filePath: 'sprites/enemies/cliff-wolf.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.ridge-hawk',
    category: 'enemy',
    intendedUse: 'Battle sprite for ridge-hawk',
    filePath: 'sprites/enemies/ridge-hawk.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.pool-wisp',
    category: 'enemy',
    intendedUse: 'Battle sprite for pool-wisp',
    filePath: 'sprites/enemies/pool-wisp.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.falls-siren',
    category: 'enemy',
    intendedUse: 'Battle sprite for falls-siren',
    filePath: 'sprites/enemies/falls-siren.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.briar-wraith',
    category: 'enemy',
    intendedUse: 'Battle sprite for briar-wraith',
    filePath: 'sprites/enemies/briar-wraith.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.cemetery-shade',
    category: 'enemy',
    intendedUse: 'Battle sprite for cemetery-shade',
    filePath: 'sprites/enemies/cemetery-shade.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.coalbound-warden',
    category: 'enemy',
    intendedUse: 'Battle sprite for coalbound-warden',
    filePath: 'sprites/enemies/coalbound-warden.svg',
    dimensions: { width: 256, height: 256 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.healing-poultice',
    category: 'icon',
    intendedUse: 'Item icon for healing-poultice',
    filePath: 'icons/healing-poultice.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.spirit-draught',
    category: 'icon',
    intendedUse: 'Item icon for spirit-draught',
    filePath: 'icons/spirit-draught.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.lantern-oil',
    category: 'icon',
    intendedUse: 'Item icon for lantern-oil',
    filePath: 'icons/lantern-oil.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.moth-dust',
    category: 'icon',
    intendedUse: 'Item icon for moth-dust',
    filePath: 'icons/moth-dust.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.rusted-token',
    category: 'icon',
    intendedUse: 'Item icon for rusted-token',
    filePath: 'icons/rusted-token.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.ember-shard',
    category: 'icon',
    intendedUse: 'Item icon for ember-shard',
    filePath: 'icons/ember-shard.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.wolf-fang',
    category: 'icon',
    intendedUse: 'Item icon for wolf-fang',
    filePath: 'icons/wolf-fang.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.silver-droplet',
    category: 'icon',
    intendedUse: 'Item icon for silver-droplet',
    filePath: 'icons/silver-droplet.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.withered-bramble',
    category: 'icon',
    intendedUse: 'Item icon for withered-bramble',
    filePath: 'icons/withered-bramble.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.stone-fragment',
    category: 'icon',
    intendedUse: 'Item icon for stone-fragment',
    filePath: 'icons/stone-fragment.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.water-fragment',
    category: 'icon',
    intendedUse: 'Item icon for water-fragment',
    filePath: 'icons/water-fragment.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.wind-fragment',
    category: 'icon',
    intendedUse: 'Item icon for wind-fragment',
    filePath: 'icons/wind-fragment.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.miners-lost-lantern',
    category: 'icon',
    intendedUse: 'Item icon for miners-lost-lantern',
    filePath: 'icons/miners-lost-lantern.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.wardens-ember-heart',
    category: 'icon',
    intendedUse: 'Item icon for wardens-ember-heart',
    filePath: 'icons/wardens-ember-heart.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.weathered-walking-staff',
    category: 'icon',
    intendedUse: 'Equipment icon for weathered-walking-staff (Walking Staff family, common)',
    filePath: 'icons/weathered-walking-staff.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.ironwood-walking-staff',
    category: 'icon',
    intendedUse: 'Equipment icon for ironwood-walking-staff (Walking Staff family, uncommon)',
    filePath: 'icons/ironwood-walking-staff.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.spiritwood-walking-staff',
    category: 'icon',
    intendedUse: 'Equipment icon for spiritwood-walking-staff (Walking Staff family, rare)',
    filePath: 'icons/spiritwood-walking-staff.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.worn-keeper-coat',
    category: 'icon',
    intendedUse: 'Equipment icon for worn-keeper-coat (Keeper Coat family, common)',
    filePath: 'icons/worn-keeper-coat.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.reinforced-keeper-coat',
    category: 'icon',
    intendedUse: 'Equipment icon for reinforced-keeper-coat (Keeper Coat family, uncommon)',
    filePath: 'icons/reinforced-keeper-coat.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.veteran-keeper-coat',
    category: 'icon',
    intendedUse: 'Equipment icon for veteran-keeper-coat (Keeper Coat family, rare)',
    filePath: 'icons/veteran-keeper-coat.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.traveler-boots',
    category: 'icon',
    intendedUse: 'Equipment icon for traveler-boots (Traveler Boots family, common)',
    filePath: 'icons/traveler-boots.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.trail-boots',
    category: 'icon',
    intendedUse: 'Equipment icon for trail-boots (Traveler Boots family, uncommon)',
    filePath: 'icons/trail-boots.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.ranger-boots',
    category: 'icon',
    intendedUse: 'Equipment icon for ranger-boots (Traveler Boots family, rare)',
    filePath: 'icons/ranger-boots.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.work-gloves',
    category: 'icon',
    intendedUse: 'Equipment icon for work-gloves (Work Gloves family, common)',
    filePath: 'icons/work-gloves.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.leather-gauntlets',
    category: 'icon',
    intendedUse: 'Equipment icon for leather-gauntlets (Work Gloves family, uncommon)',
    filePath: 'icons/leather-gauntlets.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.keepers-gauntlets',
    category: 'icon',
    intendedUse: "Equipment icon for keepers-gauntlets (Work Gloves family, rare)",
    filePath: 'icons/keepers-gauntlets.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.river-stone-charm',
    category: 'icon',
    intendedUse: 'Equipment icon for river-stone-charm (Mountain Charm family, common)',
    filePath: 'icons/river-stone-charm.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.mountain-knot',
    category: 'icon',
    intendedUse: 'Equipment icon for mountain-knot (Mountain Charm family, uncommon)',
    filePath: 'icons/mountain-knot.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.ghost-miners-coin',
    category: 'icon',
    intendedUse: "Equipment icon for ghost-miners-coin (Mountain Charm family, rare)",
    filePath: 'icons/ghost-miners-coin.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.keepers-lantern',
    category: 'icon',
    intendedUse: 'Equipment icon for keepers-lantern (Lantern of the First Promise)',
    filePath: 'icons/keepers-lantern.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.miners-lost-lantern-equipped',
    category: 'icon',
    intendedUse: 'Equipment icon for miners-lost-lantern-equipped (Lantern of Enduring Embers)',
    filePath: 'icons/miners-lost-lantern-equipped.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.stone-wolf-totem',
    category: 'icon',
    intendedUse: 'Equipment icon for stone-wolf-totem (Mountain Spirits family, rare)',
    filePath: 'icons/stone-wolf-totem.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.mountain-guardian-totem',
    category: 'icon',
    intendedUse: 'Equipment icon for mountain-guardian-totem (Mountain Spirits family, legendary)',
    filePath: 'icons/mountain-guardian-totem.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.travelers-cloak',
    category: 'icon',
    intendedUse: "Equipment icon for travelers-cloak (Prologue starting-kit armor)",
    filePath: 'icons/travelers-cloak.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.guardian-memory-fragment-1',
    category: 'icon',
    intendedUse: 'Item icon for guardian-memory-fragment-1',
    filePath: 'icons/guardian-memory-fragment-1.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.currency.gold',
    category: 'icon',
    intendedUse: 'Currency icon for gold',
    filePath: 'icons/currency-gold.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.currency.spirit-essence',
    category: 'icon',
    intendedUse: 'Currency icon for spirit-essence',
    filePath: 'icons/currency-spirit-essence.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.currency.festival-tokens',
    category: 'icon',
    intendedUse: 'Currency icon for festival-tokens',
    filePath: 'icons/currency-festival-tokens.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.currency.premium-currency',
    category: 'icon',
    intendedUse: 'Currency icon for premium-currency',
    filePath: 'icons/currency-premium-currency.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle-bg.forest',
    category: 'background',
    intendedUse: 'Full-screen battle background: generic fallback for locations with no dedicated art (Ash Hallow, interiors, and the Ironwood Trail sub-landmarks)',
    filePath: 'backgrounds/forest.svg',
    dimensions: { width: 1280, height: 720 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle-bg.shrine',
    category: 'background',
    intendedUse: 'Full-screen battle background: shrine (currently unused - no location references it)',
    filePath: 'backgrounds/shrine.svg',
    dimensions: { width: 1280, height: 720 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle-bg.ironwood-trail',
    category: 'background',
    intendedUse: 'Full-screen battle background: Ironwood Trail',
    filePath: 'backgrounds/ironwood-trail.png',
    dimensions: { width: 1672, height: 941 },
    status: 'final',
    notes: 'AI-generated illustration commissioned for this project.',
  },
  {
    id: 'battle-bg.raven-ridge',
    category: 'background',
    intendedUse: 'Full-screen battle background: Raven Ridge',
    filePath: 'backgrounds/raven-ridge.png',
    dimensions: { width: 1672, height: 941 },
    status: 'final',
    notes: 'AI-generated illustration commissioned for this project.',
  },
  {
    id: 'battle-bg.whisper-falls',
    category: 'background',
    intendedUse: 'Full-screen battle background: Whisper Falls',
    filePath: 'backgrounds/whisper-falls.png',
    dimensions: { width: 1672, height: 941 },
    status: 'final',
    notes: 'AI-generated illustration commissioned for this project.',
  },
  {
    id: 'battle-bg.black-briar-forest',
    category: 'background',
    intendedUse: 'Full-screen battle background: Black Briar Forest',
    filePath: 'backgrounds/black-briar-forest.png',
    dimensions: { width: 1672, height: 941 },
    status: 'final',
    notes: 'AI-generated illustration commissioned for this project.',
  },
  {
    id: 'battle-bg.hollow-rail-mine',
    category: 'background',
    intendedUse: 'Full-screen battle background: Hollow Rail Mine (replaces the old generic battle-bg.dungeon placeholder)',
    filePath: 'backgrounds/hollow-rail-mine.png',
    dimensions: { width: 1672, height: 941 },
    status: 'final',
    notes: 'AI-generated illustration commissioned for this project.',
  },
  {
    id: 'background.title-screen',
    category: 'background',
    intendedUse: 'Full-bleed hero art behind the Title/sign-in screen - already has the game logo and tagline baked in, so TitleScene omits its own text title over it.',
    filePath: 'backgrounds/title-screen.png',
    dimensions: { width: 1536, height: 1024 },
    status: 'final',
    notes: 'AI-generated illustration commissioned for this project.',
  },
  {
    id: 'map.ash-hallow',
    category: 'map',
    intendedUse: 'Tiled JSON map for Ash Hallow town',
    filePath: 'maps/ash-hallow.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Authored by hand to the Tiled JSON schema, using tileset.tiny-dungeon. Added in Phase 7.',
  },
  {
    id: 'map.ironwood-trail',
    category: 'map',
    intendedUse: 'Tiled JSON map for Ironwood Trail overworld',
    filePath: 'maps/ironwood-trail.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Authored by hand to the Tiled JSON schema, using tileset.tiny-dungeon. Added in Phase 8.',
  },
  {
    id: 'map.hollow-rail-mine',
    category: 'map',
    intendedUse: 'Tiled JSON map for Hollow Rail Mine dungeon',
    filePath: 'maps/hollow-rail-mine.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Authored by hand to the Tiled JSON schema, using tileset.tiny-dungeon. Added in Phase 8.',
  },
  {
    id: 'map.ash-hallow-elias-house',
    category: 'map',
    intendedUse: "Tiled JSON map for Elias Rowan's house interior, in Ash Hallow",
    filePath: 'maps/ash-hallow-elias-house.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Authored by hand to the Tiled JSON schema, using tileset.tiny-dungeon. Id namespaced by town since other villages will have their own houses/shops later.',
  },
  {
    id: 'map.ash-hallow-mara-shop',
    category: 'map',
    intendedUse: "Tiled JSON map for Mara Vale's general store interior, in Ash Hallow",
    filePath: 'maps/ash-hallow-mara-shop.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Authored by hand to the Tiled JSON schema, using tileset.tiny-dungeon. Id namespaced by town since other villages will have their own houses/shops later.',
  },
  {
    id: 'map.ash-hallow-inn',
    category: 'map',
    intendedUse: 'Tiled JSON map for the Ash Hallow Inn interior',
    filePath: 'maps/ash-hallow-inn.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Authored by hand to the Tiled JSON schema, using tileset.tiny-dungeon.',
  },
  {
    id: 'map.raven-ridge',
    category: 'map',
    intendedUse: 'Tiled JSON map for Raven Ridge overworld area',
    filePath: 'maps/raven-ridge.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Generated via scripts/genMap.mjs from scripts/map-specs/raven-ridge.json.',
  },
  {
    id: 'map.whisper-falls',
    category: 'map',
    intendedUse: 'Tiled JSON map for Whisper Falls overworld area',
    filePath: 'maps/whisper-falls.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Generated via scripts/genMap.mjs from scripts/map-specs/whisper-falls.json.',
  },
  {
    id: 'map.black-briar-forest',
    category: 'map',
    intendedUse: 'Tiled JSON map for Black Briar Forest overworld area',
    filePath: 'maps/black-briar-forest.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Generated via scripts/genMap.mjs from scripts/map-specs/black-briar-forest.json.',
  },
  {
    id: 'map.ash-hallow-blacksmith',
    category: 'map',
    intendedUse: 'Tiled JSON map for the Ash Hallow Forge (blacksmith) interior',
    filePath: 'maps/ash-hallow-blacksmith.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Generated via scripts/genMap.mjs from scripts/map-specs/ash-hallow-blacksmith.json.',
  },
  {
    id: 'map.ash-hallow-apothecary',
    category: 'map',
    intendedUse: "Tiled JSON map for Willow's Apothecary interior, in Ash Hallow",
    filePath: 'maps/ash-hallow-apothecary.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Generated via scripts/genMap.mjs from scripts/map-specs/ash-hallow-apothecary.json.',
  },
  {
    id: 'map.ash-hallow-armory',
    category: 'map',
    intendedUse: "Tiled JSON map for Tessa Ironhand's Armory interior, in Ash Hallow",
    filePath: 'maps/ash-hallow-armory.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Generated via scripts/genMap.mjs from scripts/map-specs/ash-hallow-armory.json.',
  },
  {
    id: 'map.ash-hallow-archive',
    category: 'map',
    intendedUse: 'Tiled JSON map for the Ash Hallow Archive interior (Historian Miriam)',
    filePath: 'maps/ash-hallow-archive.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Generated via scripts/genMap.mjs from scripts/map-specs/ash-hallow-archive.json.',
  },
  {
    id: 'map.ash-hallow-mine-office',
    category: 'map',
    intendedUse: 'Tiled JSON map for the Ash Hallow Mine Office interior (Silas Flint)',
    filePath: 'maps/ash-hallow-mine-office.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Generated via scripts/genMap.mjs from scripts/map-specs/ash-hallow-mine-office.json.',
  },
  {
    id: 'map.ash-hallow-town-hall',
    category: 'map',
    intendedUse: 'Tiled JSON map for Ash Hallow Town Hall interior (Mayor Eleanor Ashcroft)',
    filePath: 'maps/ash-hallow-town-hall.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Generated via scripts/genMap.mjs from scripts/map-specs/ash-hallow-town-hall.json.',
  },
  {
    id: 'structure.house',
    category: 'structure',
    intendedUse: "Overworld building-facade marker for Elias Rowan's house door in Ash Hallow",
    filePath: 'sprites/structures/house.svg',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder. Final art should be a painted building facade sized to its footprint.',
  },
  {
    id: 'structure.shop',
    category: 'structure',
    intendedUse: "Overworld building-facade marker for Mara Vale's general store door in Ash Hallow",
    filePath: 'sprites/structures/shop.svg',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder. Final art should be a painted building facade sized to its footprint.',
  },
  {
    id: 'structure.inn',
    category: 'structure',
    intendedUse: 'Overworld building-facade marker for the Ash Hallow Inn door',
    filePath: 'sprites/structures/inn.svg',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder. Final art should be a painted building facade sized to its footprint.',
  },
  {
    id: 'structure.blacksmith',
    category: 'structure',
    intendedUse: 'Overworld building-facade marker for the Ash Hallow Forge door',
    filePath: 'sprites/structures/blacksmith.svg',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder. Final art should be a painted building facade sized to its footprint.',
  },
  {
    id: 'structure.apothecary',
    category: 'structure',
    intendedUse: "Overworld building-facade marker for Willow's Apothecary door in Ash Hallow",
    filePath: 'sprites/structures/apothecary.svg',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder. Final art should be a painted building facade sized to its footprint.',
  },
  {
    id: 'structure.armory',
    category: 'structure',
    intendedUse: 'Overworld building-facade marker for the Ash Hallow Armory door',
    filePath: 'sprites/structures/armory.svg',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder. Final art should be a painted building facade sized to its footprint.',
  },
  {
    id: 'structure.archive',
    category: 'structure',
    intendedUse: 'Overworld building-facade marker for the Ash Hallow Archive door',
    filePath: 'sprites/structures/archive.svg',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder. Final art should be a painted building facade sized to its footprint.',
  },
  {
    id: 'structure.mine-office',
    category: 'structure',
    intendedUse: 'Overworld building-facade marker for the Ash Hallow Mine Office door',
    filePath: 'sprites/structures/mine-office.svg',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder. Final art should be a painted building facade sized to its footprint.',
  },
  {
    id: 'structure.town-hall',
    category: 'structure',
    intendedUse: 'Overworld building-facade marker for Ash Hallow Town Hall door',
    filePath: 'sprites/structures/town-hall.svg',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder. Final art should be a painted building facade sized to its footprint.',
  },
  {
    id: 'structure.shrine',
    category: 'structure',
    intendedUse: 'Marker for shrine/landmark interactables in overworld locations (e.g. Spirit Grove)',
    filePath: 'sprites/structures/shrine.svg',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder. Final art should be a weathered stone shrine.',
  },
  {
    id: 'structure.chest',
    category: 'structure',
    intendedUse: 'Marker for treasure chest interactables in overworld/dungeon locations',
    filePath: 'sprites/structures/chest.svg',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder. Same sprite is reused for opened chests (label text distinguishes the state).',
  },
];

export function findAsset(id: string): AssetDefinition | undefined {
  return ASSET_REGISTRY.find((a) => a.id === id);
}

export function listAssetsByCategory(category: AssetCategory): AssetDefinition[] {
  return ASSET_REGISTRY.filter((a) => a.category === category);
}
