export type AssetCategory =
  | 'character'
  | 'enemy'
  | 'portrait'
  | 'tileset'
  | 'map'
  | 'ui'
  | 'icon'
  | 'background'
  | 'audio'
  | 'structure';

export type AssetStatus = 'placeholder' | 'final';

export interface AssetDimensions {
  width: number;
  height: number;
}

export interface AssetDefinition {
  id: string;
  category: AssetCategory;
  intendedUse: string;
  /** Path relative to /assets/ under public/, e.g. "sprites/characters/player.png". */
  filePath: string;
  /** null for asset types dimensions don't apply to (audio, Tiled maps). */
  dimensions: AssetDimensions | null;
  status: AssetStatus;
  notes: string;
}

/**
 * Single source of truth for every game asset. Code never imports an image/audio/map
 * file path directly — it looks the asset up here by id via assetManager.getAsset().
 * Swapping a placeholder for final art is a one-line edit to this file.
 */
export const ASSET_REGISTRY: AssetDefinition[] = [
  {
    id: 'tileset.tiny-dungeon',
    category: 'tileset',
    intendedUse: 'Shared 16x16 tileset for Ash Hallow, Ironwood Trail, and Hollow Rail Mine maps (walls, floors, dungeon/town dressing)',
    filePath: 'tilesets/tiny-dungeon.png',
    dimensions: { width: 192, height: 176 },
    status: 'placeholder',
    notes: 'Kenney "Tiny Dungeon" pack, CC0 1.0, kenney.nl/assets/tiny-dungeon. 12x11 grid of 16x16 tiles.',
  },
  {
    id: 'ui.panel-border-default',
    category: 'ui',
    intendedUse: 'Default 9-slice panel background for dialogue box, menus, and other JRPG UI panels',
    filePath: 'ui/panel-border-000.png',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Kenney "Fantasy UI Borders" pack, CC0 1.0, kenney.nl/assets/fantasy-ui-borders. Use as CSS border-image with ~16px slice insets.',
  },
  {
    id: 'ui.panel-border-accent',
    category: 'ui',
    intendedUse: 'Accent 9-slice panel background for emphasized UI (e.g. victory/level-up panels)',
    filePath: 'ui/panel-border-004.png',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Kenney "Fantasy UI Borders" pack, CC0 1.0, kenney.nl/assets/fantasy-ui-borders. Use as CSS border-image with ~16px slice insets.',
  },
  {
    id: 'portrait.elias-rowan',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for elias-rowan',
    filePath: 'portraits/elias-rowan.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.elias-rowan',
    category: 'character',
    intendedUse: 'Overworld sprite for elias-rowan (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/elias-rowan.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.mara-vale',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for mara-vale',
    filePath: 'portraits/mara-vale.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.mara-vale',
    category: 'character',
    intendedUse: 'Overworld sprite for mara-vale (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/mara-vale.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.silas-flint',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for silas-flint',
    filePath: 'portraits/silas-flint.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.silas-flint',
    category: 'character',
    intendedUse: 'Overworld sprite for silas-flint (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/silas-flint.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.juniper-reed',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for juniper-reed',
    filePath: 'portraits/juniper-reed.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.juniper-reed',
    category: 'character',
    intendedUse: 'Overworld sprite for juniper-reed (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/juniper-reed.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.nell-ashby',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for nell-ashby',
    filePath: 'portraits/nell-ashby.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.nell-ashby',
    category: 'character',
    intendedUse: 'Overworld sprite for nell-ashby (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/nell-ashby.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.player',
    category: 'character',
    intendedUse: 'Player overworld sprite (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/player.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.mothling',
    category: 'enemy',
    intendedUse: 'Battle sprite for mothling',
    filePath: 'sprites/enemies/mothling.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.greater-mothling',
    category: 'enemy',
    intendedUse: 'Battle sprite for greater-mothling',
    filePath: 'sprites/enemies/greater-mothling.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.restless-miner',
    category: 'enemy',
    intendedUse: 'Battle sprite for restless-miner',
    filePath: 'sprites/enemies/restless-miner.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.foreman-wraith',
    category: 'enemy',
    intendedUse: 'Battle sprite for foreman-wraith',
    filePath: 'sprites/enemies/foreman-wraith.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.coal-spirit',
    category: 'enemy',
    intendedUse: 'Battle sprite for coal-spirit',
    filePath: 'sprites/enemies/coal-spirit.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.coal-wraith',
    category: 'enemy',
    intendedUse: 'Battle sprite for coal-wraith',
    filePath: 'sprites/enemies/coal-wraith.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.coalbound-warden',
    category: 'enemy',
    intendedUse: 'Battle sprite for coalbound-warden',
    filePath: 'sprites/enemies/coalbound-warden.svg',
    dimensions: { width: 256, height: 256 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.healing-poultice',
    category: 'icon',
    intendedUse: 'Item icon for healing-poultice',
    filePath: 'icons/healing-poultice.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.spirit-draught',
    category: 'icon',
    intendedUse: 'Item icon for spirit-draught',
    filePath: 'icons/spirit-draught.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.lantern-oil',
    category: 'icon',
    intendedUse: 'Item icon for lantern-oil',
    filePath: 'icons/lantern-oil.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.moth-dust',
    category: 'icon',
    intendedUse: 'Item icon for moth-dust',
    filePath: 'icons/moth-dust.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.rusted-token',
    category: 'icon',
    intendedUse: 'Item icon for rusted-token',
    filePath: 'icons/rusted-token.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.ember-shard',
    category: 'icon',
    intendedUse: 'Item icon for ember-shard',
    filePath: 'icons/ember-shard.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.miners-lost-lantern',
    category: 'icon',
    intendedUse: 'Item icon for miners-lost-lantern',
    filePath: 'icons/miners-lost-lantern.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.wardens-ember-heart',
    category: 'icon',
    intendedUse: 'Item icon for wardens-ember-heart',
    filePath: 'icons/wardens-ember-heart.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.miners-pick',
    category: 'icon',
    intendedUse: 'Equipment icon for miners-pick',
    filePath: 'icons/miners-pick.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.keepers-lantern-staff',
    category: 'icon',
    intendedUse: 'Equipment icon for keepers-lantern-staff',
    filePath: 'icons/keepers-lantern-staff.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.travelers-coat',
    category: 'icon',
    intendedUse: 'Equipment icon for travelers-coat',
    filePath: 'icons/travelers-coat.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.ironwood-vest',
    category: 'icon',
    intendedUse: 'Equipment icon for ironwood-vest',
    filePath: 'icons/ironwood-vest.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.worn-trail-boots',
    category: 'icon',
    intendedUse: 'Equipment icon for worn-trail-boots',
    filePath: 'icons/worn-trail-boots.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.ridge-runner-boots',
    category: 'icon',
    intendedUse: 'Equipment icon for ridge-runner-boots',
    filePath: 'icons/ridge-runner-boots.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.frayed-gloves',
    category: 'icon',
    intendedUse: 'Equipment icon for frayed-gloves',
    filePath: 'icons/frayed-gloves.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.miners-leather-gloves',
    category: 'icon',
    intendedUse: 'Equipment icon for miners-leather-gloves',
    filePath: 'icons/miners-leather-gloves.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.ash-hallow-token',
    category: 'icon',
    intendedUse: 'Equipment icon for ash-hallow-token',
    filePath: 'icons/ash-hallow-token.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.moonlit-charm',
    category: 'icon',
    intendedUse: 'Equipment icon for moonlit-charm',
    filePath: 'icons/moonlit-charm.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.keepers-lantern',
    category: 'icon',
    intendedUse: 'Equipment icon for keepers-lantern',
    filePath: 'icons/keepers-lantern.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.miners-lost-lantern-equipped',
    category: 'icon',
    intendedUse: 'Equipment icon for miners-lost-lantern-equipped',
    filePath: 'icons/miners-lost-lantern-equipped.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.carved-totem',
    category: 'icon',
    intendedUse: 'Equipment icon for carved-totem',
    filePath: 'icons/carved-totem.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.currency.gold',
    category: 'icon',
    intendedUse: 'Currency icon for gold',
    filePath: 'icons/currency-gold.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.currency.spirit-essence',
    category: 'icon',
    intendedUse: 'Currency icon for spirit-essence',
    filePath: 'icons/currency-spirit-essence.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.currency.festival-tokens',
    category: 'icon',
    intendedUse: 'Currency icon for festival-tokens',
    filePath: 'icons/currency-festival-tokens.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.currency.premium-currency',
    category: 'icon',
    intendedUse: 'Currency icon for premium-currency',
    filePath: 'icons/currency-premium-currency.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle-bg.forest',
    category: 'background',
    intendedUse: 'Full-screen battle background: forest',
    filePath: 'backgrounds/forest.svg',
    dimensions: { width: 1280, height: 720 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle-bg.dungeon',
    category: 'background',
    intendedUse: 'Full-screen battle background: dungeon',
    filePath: 'backgrounds/dungeon.svg',
    dimensions: { width: 1280, height: 720 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle-bg.shrine',
    category: 'background',
    intendedUse: 'Full-screen battle background: shrine',
    filePath: 'backgrounds/shrine.svg',
    dimensions: { width: 1280, height: 720 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'map.ash-hallow',
    category: 'map',
    intendedUse: 'Tiled JSON map for Ash Hallow town',
    filePath: 'maps/ash-hallow.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Authored by hand to the Tiled JSON schema, using tileset.tiny-dungeon. Added in Phase 7.',
  },
  {
    id: 'map.ironwood-trail',
    category: 'map',
    intendedUse: 'Tiled JSON map for Ironwood Trail overworld',
    filePath: 'maps/ironwood-trail.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Authored by hand to the Tiled JSON schema, using tileset.tiny-dungeon. Added in Phase 8.',
  },
  {
    id: 'map.hollow-rail-mine',
    category: 'map',
    intendedUse: 'Tiled JSON map for Hollow Rail Mine dungeon',
    filePath: 'maps/hollow-rail-mine.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Authored by hand to the Tiled JSON schema, using tileset.tiny-dungeon. Added in Phase 8.',
  },
  {
    id: 'map.ash-hallow-elias-house',
    category: 'map',
    intendedUse: "Tiled JSON map for Elias Rowan's house interior, in Ash Hallow",
    filePath: 'maps/ash-hallow-elias-house.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Authored by hand to the Tiled JSON schema, using tileset.tiny-dungeon. Id namespaced by town since other villages will have their own houses/shops later.',
  },
  {
    id: 'map.ash-hallow-mara-shop',
    category: 'map',
    intendedUse: "Tiled JSON map for Mara Vale's general store interior, in Ash Hallow",
    filePath: 'maps/ash-hallow-mara-shop.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Authored by hand to the Tiled JSON schema, using tileset.tiny-dungeon. Id namespaced by town since other villages will have their own houses/shops later.',
  },
  {
    id: 'map.ash-hallow-inn',
    category: 'map',
    intendedUse: 'Tiled JSON map for the Ash Hallow Inn interior',
    filePath: 'maps/ash-hallow-inn.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Authored by hand to the Tiled JSON schema, using tileset.tiny-dungeon.',
  },
  {
    id: 'structure.house',
    category: 'structure',
    intendedUse: "Overworld building-facade marker for Elias Rowan's house door in Ash Hallow",
    filePath: 'sprites/structures/house.svg',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder. Final art should be a painted building facade sized to its footprint.',
  },
  {
    id: 'structure.shop',
    category: 'structure',
    intendedUse: "Overworld building-facade marker for Mara Vale's general store door in Ash Hallow",
    filePath: 'sprites/structures/shop.svg',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder. Final art should be a painted building facade sized to its footprint.',
  },
  {
    id: 'structure.inn',
    category: 'structure',
    intendedUse: 'Overworld building-facade marker for the Ash Hallow Inn door',
    filePath: 'sprites/structures/inn.svg',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder. Final art should be a painted building facade sized to its footprint.',
  },
];

export function findAsset(id: string): AssetDefinition | undefined {
  return ASSET_REGISTRY.find((a) => a.id === id);
}

export function listAssetsByCategory(category: AssetCategory): AssetDefinition[] {
  return ASSET_REGISTRY.filter((a) => a.category === category);
}
