export type AssetCategory =
  | 'character'
  | 'enemy'
  | 'portrait'
  | 'tileset'
  | 'map'
  | 'ui'
  | 'icon'
  | 'background'
  | 'audio'
  | 'structure';

export type AssetStatus = 'placeholder' | 'final';

export interface AssetDimensions {
  width: number;
  height: number;
}

export interface AssetDefinition {
  id: string;
  category: AssetCategory;
  intendedUse: string;
  /** Path relative to /assets/ under public/, e.g. "sprites/characters/player.png". */
  filePath: string;
  /** null for asset types dimensions don't apply to (audio, Tiled maps). */
  dimensions: AssetDimensions | null;
  status: AssetStatus;
  notes: string;
}

/**
 * Single source of truth for every game asset. Code never imports an image/audio/map
 * file path directly — it looks the asset up here by id via assetManager.getAsset().
 * Swapping a placeholder for final art is a one-line edit to this file.
 */
export const ASSET_REGISTRY: AssetDefinition[] = [
  {
    id: 'tileset.tiny-dungeon',
    category: 'tileset',
    intendedUse: 'Shared 16x16 tileset for Ash Hallow, Ironwood Trail, and Hollow Rail Mine maps (walls, floors, dungeon/town dressing)',
    filePath: 'tilesets/tiny-dungeon.png',
    dimensions: { width: 192, height: 176 },
    status: 'placeholder',
    notes: 'Kenney "Tiny Dungeon" pack, CC0 1.0, kenney.nl/assets/tiny-dungeon. 12x11 grid of 16x16 tiles.',
  },
  {
    id: 'ui.panel-border-default',
    category: 'ui',
    intendedUse: 'Default 9-slice panel background for dialogue box, menus, and other JRPG UI panels',
    filePath: 'ui/panel-border-000.png',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Kenney "Fantasy UI Borders" pack, CC0 1.0, kenney.nl/assets/fantasy-ui-borders. Use as CSS border-image with ~16px slice insets.',
  },
  {
    id: 'ui.panel-border-accent',
    category: 'ui',
    intendedUse: 'Accent 9-slice panel background for emphasized UI (e.g. victory/level-up panels)',
    filePath: 'ui/panel-border-004.png',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Kenney "Fantasy UI Borders" pack, CC0 1.0, kenney.nl/assets/fantasy-ui-borders. Use as CSS border-image with ~16px slice insets.',
  },
  {
    id: 'portrait.elias-rowan',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for elias-rowan',
    filePath: 'portraits/elias-rowan.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.elias-rowan',
    category: 'character',
    intendedUse: 'Overworld sprite for elias-rowan (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/elias-rowan.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.mara-vale',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for mara-vale',
    filePath: 'portraits/mara-vale.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.mara-vale',
    category: 'character',
    intendedUse: 'Overworld sprite for mara-vale (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/mara-vale.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.silas-flint',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for silas-flint',
    filePath: 'portraits/silas-flint.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.silas-flint',
    category: 'character',
    intendedUse: 'Overworld sprite for silas-flint (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/silas-flint.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.juniper-reed',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for juniper-reed',
    filePath: 'portraits/juniper-reed.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.juniper-reed',
    category: 'character',
    intendedUse: 'Overworld sprite for juniper-reed (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/juniper-reed.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.nell-ashby',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for nell-ashby',
    filePath: 'portraits/nell-ashby.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.nell-ashby',
    category: 'character',
    intendedUse: 'Overworld sprite for nell-ashby (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/nell-ashby.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.tobias-hearn',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for tobias-hearn',
    filePath: 'portraits/tobias-hearn.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.tobias-hearn',
    category: 'character',
    intendedUse: 'Overworld sprite for tobias-hearn (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/tobias-hearn.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.wren-callahan',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for wren-callahan',
    filePath: 'portraits/wren-callahan.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.wren-callahan',
    category: 'character',
    intendedUse: 'Overworld sprite for wren-callahan (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/wren-callahan.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.faye-whitlock',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for faye-whitlock',
    filePath: 'portraits/faye-whitlock.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.faye-whitlock',
    category: 'character',
    intendedUse: 'Overworld sprite for faye-whitlock (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/faye-whitlock.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.reeve-talbot',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for reeve-talbot',
    filePath: 'portraits/reeve-talbot.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.reeve-talbot',
    category: 'character',
    intendedUse: 'Overworld sprite for reeve-talbot (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/reeve-talbot.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'portrait.mayor-osric-bell',
    category: 'portrait',
    intendedUse: 'Dialogue portrait for mayor-osric-bell',
    filePath: 'portraits/mayor-osric-bell.svg',
    dimensions: { width: 512, height: 512 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.npc.mayor-osric-bell',
    category: 'character',
    intendedUse: 'Overworld sprite for mayor-osric-bell (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/mayor-osric-bell.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'sprite.player',
    category: 'character',
    intendedUse: 'Player overworld sprite (single-frame placeholder; final art should be a 32x32 4-direction idle+walk sheet)',
    filePath: 'sprites/characters/player.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.mothling',
    category: 'enemy',
    intendedUse: 'Battle sprite for mothling',
    filePath: 'sprites/enemies/mothling.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.greater-mothling',
    category: 'enemy',
    intendedUse: 'Battle sprite for greater-mothling',
    filePath: 'sprites/enemies/greater-mothling.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.restless-miner',
    category: 'enemy',
    intendedUse: 'Battle sprite for restless-miner',
    filePath: 'sprites/enemies/restless-miner.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.foreman-wraith',
    category: 'enemy',
    intendedUse: 'Battle sprite for foreman-wraith',
    filePath: 'sprites/enemies/foreman-wraith.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.coal-spirit',
    category: 'enemy',
    intendedUse: 'Battle sprite for coal-spirit',
    filePath: 'sprites/enemies/coal-spirit.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.coal-wraith',
    category: 'enemy',
    intendedUse: 'Battle sprite for coal-wraith',
    filePath: 'sprites/enemies/coal-wraith.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.cliff-wolf',
    category: 'enemy',
    intendedUse: 'Battle sprite for cliff-wolf',
    filePath: 'sprites/enemies/cliff-wolf.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.ridge-hawk',
    category: 'enemy',
    intendedUse: 'Battle sprite for ridge-hawk',
    filePath: 'sprites/enemies/ridge-hawk.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.pool-wisp',
    category: 'enemy',
    intendedUse: 'Battle sprite for pool-wisp',
    filePath: 'sprites/enemies/pool-wisp.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.falls-siren',
    category: 'enemy',
    intendedUse: 'Battle sprite for falls-siren',
    filePath: 'sprites/enemies/falls-siren.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.briar-wraith',
    category: 'enemy',
    intendedUse: 'Battle sprite for briar-wraith',
    filePath: 'sprites/enemies/briar-wraith.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.cemetery-shade',
    category: 'enemy',
    intendedUse: 'Battle sprite for cemetery-shade',
    filePath: 'sprites/enemies/cemetery-shade.svg',
    dimensions: { width: 128, height: 128 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle.enemy.coalbound-warden',
    category: 'enemy',
    intendedUse: 'Battle sprite for coalbound-warden',
    filePath: 'sprites/enemies/coalbound-warden.svg',
    dimensions: { width: 256, height: 256 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.healing-poultice',
    category: 'icon',
    intendedUse: 'Item icon for healing-poultice',
    filePath: 'icons/healing-poultice.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.spirit-draught',
    category: 'icon',
    intendedUse: 'Item icon for spirit-draught',
    filePath: 'icons/spirit-draught.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.lantern-oil',
    category: 'icon',
    intendedUse: 'Item icon for lantern-oil',
    filePath: 'icons/lantern-oil.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.moth-dust',
    category: 'icon',
    intendedUse: 'Item icon for moth-dust',
    filePath: 'icons/moth-dust.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.rusted-token',
    category: 'icon',
    intendedUse: 'Item icon for rusted-token',
    filePath: 'icons/rusted-token.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.ember-shard',
    category: 'icon',
    intendedUse: 'Item icon for ember-shard',
    filePath: 'icons/ember-shard.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.wolf-fang',
    category: 'icon',
    intendedUse: 'Item icon for wolf-fang',
    filePath: 'icons/wolf-fang.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.silver-droplet',
    category: 'icon',
    intendedUse: 'Item icon for silver-droplet',
    filePath: 'icons/silver-droplet.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.withered-bramble',
    category: 'icon',
    intendedUse: 'Item icon for withered-bramble',
    filePath: 'icons/withered-bramble.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.miners-lost-lantern',
    category: 'icon',
    intendedUse: 'Item icon for miners-lost-lantern',
    filePath: 'icons/miners-lost-lantern.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.item.wardens-ember-heart',
    category: 'icon',
    intendedUse: 'Item icon for wardens-ember-heart',
    filePath: 'icons/wardens-ember-heart.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.weathered-walking-staff',
    category: 'icon',
    intendedUse: 'Equipment icon for weathered-walking-staff (Walking Staff family, common)',
    filePath: 'icons/weathered-walking-staff.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.ironwood-walking-staff',
    category: 'icon',
    intendedUse: 'Equipment icon for ironwood-walking-staff (Walking Staff family, uncommon)',
    filePath: 'icons/ironwood-walking-staff.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.spiritwood-walking-staff',
    category: 'icon',
    intendedUse: 'Equipment icon for spiritwood-walking-staff (Walking Staff family, rare)',
    filePath: 'icons/spiritwood-walking-staff.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.worn-keeper-coat',
    category: 'icon',
    intendedUse: 'Equipment icon for worn-keeper-coat (Keeper Coat family, common)',
    filePath: 'icons/worn-keeper-coat.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.reinforced-keeper-coat',
    category: 'icon',
    intendedUse: 'Equipment icon for reinforced-keeper-coat (Keeper Coat family, uncommon)',
    filePath: 'icons/reinforced-keeper-coat.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.veteran-keeper-coat',
    category: 'icon',
    intendedUse: 'Equipment icon for veteran-keeper-coat (Keeper Coat family, rare)',
    filePath: 'icons/veteran-keeper-coat.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.traveler-boots',
    category: 'icon',
    intendedUse: 'Equipment icon for traveler-boots (Traveler Boots family, common)',
    filePath: 'icons/traveler-boots.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.trail-boots',
    category: 'icon',
    intendedUse: 'Equipment icon for trail-boots (Traveler Boots family, uncommon)',
    filePath: 'icons/trail-boots.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.ranger-boots',
    category: 'icon',
    intendedUse: 'Equipment icon for ranger-boots (Traveler Boots family, rare)',
    filePath: 'icons/ranger-boots.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.work-gloves',
    category: 'icon',
    intendedUse: 'Equipment icon for work-gloves (Work Gloves family, common)',
    filePath: 'icons/work-gloves.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.leather-gauntlets',
    category: 'icon',
    intendedUse: 'Equipment icon for leather-gauntlets (Work Gloves family, uncommon)',
    filePath: 'icons/leather-gauntlets.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.keepers-gauntlets',
    category: 'icon',
    intendedUse: "Equipment icon for keepers-gauntlets (Work Gloves family, rare)",
    filePath: 'icons/keepers-gauntlets.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.river-stone-charm',
    category: 'icon',
    intendedUse: 'Equipment icon for river-stone-charm (Mountain Charm family, common)',
    filePath: 'icons/river-stone-charm.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.mountain-knot',
    category: 'icon',
    intendedUse: 'Equipment icon for mountain-knot (Mountain Charm family, uncommon)',
    filePath: 'icons/mountain-knot.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.ghost-miners-coin',
    category: 'icon',
    intendedUse: "Equipment icon for ghost-miners-coin (Mountain Charm family, rare)",
    filePath: 'icons/ghost-miners-coin.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.keepers-lantern',
    category: 'icon',
    intendedUse: 'Equipment icon for keepers-lantern (Lantern of the First Promise)',
    filePath: 'icons/keepers-lantern.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.miners-lost-lantern-equipped',
    category: 'icon',
    intendedUse: 'Equipment icon for miners-lost-lantern-equipped (Lantern of Enduring Embers)',
    filePath: 'icons/miners-lost-lantern-equipped.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.equipment.stone-wolf-totem',
    category: 'icon',
    intendedUse: 'Equipment icon for stone-wolf-totem (Mountain Spirits family, rare)',
    filePath: 'icons/stone-wolf-totem.svg',
    dimensions: { width: 64, height: 64 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.currency.gold',
    category: 'icon',
    intendedUse: 'Currency icon for gold',
    filePath: 'icons/currency-gold.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.currency.spirit-essence',
    category: 'icon',
    intendedUse: 'Currency icon for spirit-essence',
    filePath: 'icons/currency-spirit-essence.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.currency.festival-tokens',
    category: 'icon',
    intendedUse: 'Currency icon for festival-tokens',
    filePath: 'icons/currency-festival-tokens.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'icon.currency.premium-currency',
    category: 'icon',
    intendedUse: 'Currency icon for premium-currency',
    filePath: 'icons/currency-premium-currency.svg',
    dimensions: { width: 32, height: 32 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle-bg.forest',
    category: 'background',
    intendedUse: 'Full-screen battle background: forest',
    filePath: 'backgrounds/forest.svg',
    dimensions: { width: 1280, height: 720 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle-bg.dungeon',
    category: 'background',
    intendedUse: 'Full-screen battle background: dungeon',
    filePath: 'backgrounds/dungeon.svg',
    dimensions: { width: 1280, height: 720 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'battle-bg.shrine',
    category: 'background',
    intendedUse: 'Full-screen battle background: shrine',
    filePath: 'backgrounds/shrine.svg',
    dimensions: { width: 1280, height: 720 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder.',
  },
  {
    id: 'map.ash-hallow',
    category: 'map',
    intendedUse: 'Tiled JSON map for Ash Hallow town',
    filePath: 'maps/ash-hallow.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Authored by hand to the Tiled JSON schema, using tileset.tiny-dungeon. Added in Phase 7.',
  },
  {
    id: 'map.ironwood-trail',
    category: 'map',
    intendedUse: 'Tiled JSON map for Ironwood Trail overworld',
    filePath: 'maps/ironwood-trail.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Authored by hand to the Tiled JSON schema, using tileset.tiny-dungeon. Added in Phase 8.',
  },
  {
    id: 'map.hollow-rail-mine',
    category: 'map',
    intendedUse: 'Tiled JSON map for Hollow Rail Mine dungeon',
    filePath: 'maps/hollow-rail-mine.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Authored by hand to the Tiled JSON schema, using tileset.tiny-dungeon. Added in Phase 8.',
  },
  {
    id: 'map.ash-hallow-elias-house',
    category: 'map',
    intendedUse: "Tiled JSON map for Elias Rowan's house interior, in Ash Hallow",
    filePath: 'maps/ash-hallow-elias-house.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Authored by hand to the Tiled JSON schema, using tileset.tiny-dungeon. Id namespaced by town since other villages will have their own houses/shops later.',
  },
  {
    id: 'map.ash-hallow-mara-shop',
    category: 'map',
    intendedUse: "Tiled JSON map for Mara Vale's general store interior, in Ash Hallow",
    filePath: 'maps/ash-hallow-mara-shop.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Authored by hand to the Tiled JSON schema, using tileset.tiny-dungeon. Id namespaced by town since other villages will have their own houses/shops later.',
  },
  {
    id: 'map.ash-hallow-inn',
    category: 'map',
    intendedUse: 'Tiled JSON map for the Ash Hallow Inn interior',
    filePath: 'maps/ash-hallow-inn.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Authored by hand to the Tiled JSON schema, using tileset.tiny-dungeon.',
  },
  {
    id: 'map.raven-ridge',
    category: 'map',
    intendedUse: 'Tiled JSON map for Raven Ridge overworld area',
    filePath: 'maps/raven-ridge.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Generated via scripts/genMap.mjs from scripts/map-specs/raven-ridge.json.',
  },
  {
    id: 'map.whisper-falls',
    category: 'map',
    intendedUse: 'Tiled JSON map for Whisper Falls overworld area',
    filePath: 'maps/whisper-falls.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Generated via scripts/genMap.mjs from scripts/map-specs/whisper-falls.json.',
  },
  {
    id: 'map.black-briar-forest',
    category: 'map',
    intendedUse: 'Tiled JSON map for Black Briar Forest overworld area',
    filePath: 'maps/black-briar-forest.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Generated via scripts/genMap.mjs from scripts/map-specs/black-briar-forest.json.',
  },
  {
    id: 'map.ash-hallow-blacksmith',
    category: 'map',
    intendedUse: 'Tiled JSON map for the Ash Hallow Forge (blacksmith) interior',
    filePath: 'maps/ash-hallow-blacksmith.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Generated via scripts/genMap.mjs from scripts/map-specs/ash-hallow-blacksmith.json.',
  },
  {
    id: 'map.ash-hallow-apothecary',
    category: 'map',
    intendedUse: "Tiled JSON map for Wren's Apothecary interior, in Ash Hallow",
    filePath: 'maps/ash-hallow-apothecary.json',
    dimensions: null,
    status: 'placeholder',
    notes: 'Generated via scripts/genMap.mjs from scripts/map-specs/ash-hallow-apothecary.json.',
  },
  {
    id: 'structure.house',
    category: 'structure',
    intendedUse: "Overworld building-facade marker for Elias Rowan's house door in Ash Hallow",
    filePath: 'sprites/structures/house.svg',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder. Final art should be a painted building facade sized to its footprint.',
  },
  {
    id: 'structure.shop',
    category: 'structure',
    intendedUse: "Overworld building-facade marker for Mara Vale's general store door in Ash Hallow",
    filePath: 'sprites/structures/shop.svg',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder. Final art should be a painted building facade sized to its footprint.',
  },
  {
    id: 'structure.inn',
    category: 'structure',
    intendedUse: 'Overworld building-facade marker for the Ash Hallow Inn door',
    filePath: 'sprites/structures/inn.svg',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder. Final art should be a painted building facade sized to its footprint.',
  },
  {
    id: 'structure.blacksmith',
    category: 'structure',
    intendedUse: 'Overworld building-facade marker for the Ash Hallow Forge door',
    filePath: 'sprites/structures/blacksmith.svg',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder. Final art should be a painted building facade sized to its footprint.',
  },
  {
    id: 'structure.apothecary',
    category: 'structure',
    intendedUse: "Overworld building-facade marker for Wren's Apothecary door in Ash Hallow",
    filePath: 'sprites/structures/apothecary.svg',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder. Final art should be a painted building facade sized to its footprint.',
  },
  {
    id: 'structure.shrine',
    category: 'structure',
    intendedUse: 'Marker for the Guardian of Ironwood shrine interactable on Ironwood Trail',
    filePath: 'sprites/structures/shrine.svg',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder. Final art should be a weathered stone shrine.',
  },
  {
    id: 'structure.chest',
    category: 'structure',
    intendedUse: 'Marker for treasure chest interactables in overworld/dungeon locations',
    filePath: 'sprites/structures/chest.svg',
    dimensions: { width: 48, height: 48 },
    status: 'placeholder',
    notes: 'Generated SVG placeholder. Same sprite is reused for opened chests (label text distinguishes the state).',
  },
];

export function findAsset(id: string): AssetDefinition | undefined {
  return ASSET_REGISTRY.find((a) => a.id === id);
}

export function listAssetsByCategory(category: AssetCategory): AssetDefinition[] {
  return ASSET_REGISTRY.filter((a) => a.category === category);
}
